name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.*

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v4
        with:
          version: 11
      - name: build
        run: |
          pnpm install
          pnpm build

      - name: Package release
        run: |
          cp ./dist/index.js ./rcm.js

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref == 'refs/heads/main' && 'nightly' || github.ref_name }}
          name: ${{ github.ref == 'refs/heads/main' && 'Nightly Release' || github.ref_name }}
          files: |
            rcm.js
